// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxV1PNxX2n5kG58bPH2HXypaYXU7031UI',
    appId: '1:553499657460:web:7cffabf904e4b09b1e8aa1',
    messagingSenderId: '553499657460',
    projectId: 'test-firebase-b5b41',
    authDomain: 'test-firebase-b5b41.firebaseapp.com',
    storageBucket: 'test-firebase-b5b41.appspot.com',
    measurementId: 'G-ZV1QYLV3T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4cB8msj4IYree6ns8rENxfT2GdJdicg',
    appId: '1:553499657460:android:1dc75cb97e216d6e1e8aa1',
    messagingSenderId: '553499657460',
    projectId: 'test-firebase-b5b41',
    storageBucket: 'test-firebase-b5b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcq72MDBRmJtABgDy_NzmxZ9BlidQWv_w',
    appId: '1:553499657460:ios:8dd6955e247003311e8aa1',
    messagingSenderId: '553499657460',
    projectId: 'test-firebase-b5b41',
    storageBucket: 'test-firebase-b5b41.appspot.com',
    iosBundleId: 'com.example.keyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcq72MDBRmJtABgDy_NzmxZ9BlidQWv_w',
    appId: '1:553499657460:ios:bab06fa49c9ef59d1e8aa1',
    messagingSenderId: '553499657460',
    projectId: 'test-firebase-b5b41',
    storageBucket: 'test-firebase-b5b41.appspot.com',
    iosBundleId: 'com.example.keyApp.RunnerTests',
  );
}
